Repository bounswe/bounswe2020group7, pull requests merged in 2020-05, with the labels that each got.

#68 Search Endpoint
  .gitignore
  practice-app/platon_api/db.sqlite3
  practice-app/platon_api/platon_api/__init__.py
  practice-app/platon_api/platon_api/__pycache__/__init__.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/settings.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/urls.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/wsgi.cpython-38.pyc
  practice-app/platon_api/platon_api/settings.py
  practice-app/platon_api/platon_api/urls.py
  practice-app/platon_api/requirements.txt
  practice-app/platon_api/rest_api/__pycache__/__init__.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/admin.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/models.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/tests.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/views.cpython-38.pyc
  practice-app/platon_api/rest_api/migrations/0001_initial.py
  practice-app/platon_api/rest_api/migrations/__pycache__/0001_initial.cpython-38.pyc
  practice-app/platon_api/rest_api/migrations/__pycache__/__init__.cpython-38.pyc
  practice-app/platon_api/rest_api/models.py
  practice-app/platon_api/rest_api/search_engine/__pycache__/search_engine.cpython-38.pyc
  practice-app/platon_api/rest_api/search_engine/documentation/search_engine.html
  practice-app/platon_api/rest_api/search_engine/documentation/search_engine_documentation.md
  practice-app/platon_api/rest_api/search_engine/search_engine.py
  practice-app/platon_api/rest_api/search_engine/test/__pycache__/test_search.cpython-38.pyc
  practice-app/platon_api/rest_api/search_engine/test/test_search.py
  practice-app/platon_api/rest_api/tests.py
  practice-app/platon_api/rest_api/views.py
Labels: Priority: High, Status: Under review, Type: New Feature

#67 Practice app register
  practice-app/platon_api/Dockerfile
  practice-app/platon_api/docker-compose.yml
  practice-app/platon_api/manage.py
  practice-app/platon_api/platon_api/__init__.py
  practice-app/platon_api/platon_api/__pycache__/__init__.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/settings.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/urls.cpython-38.pyc
  practice-app/platon_api/platon_api/asgi.py
  practice-app/platon_api/platon_api/settings.py
  practice-app/platon_api/platon_api/urls.py
  practice-app/platon_api/platon_api/wsgi.py
  practice-app/platon_api/rest_api/__init__.py
  practice-app/platon_api/rest_api/admin.py
  practice-app/platon_api/rest_api/apps.py
  practice-app/platon_api/rest_api/models.py
  practice-app/platon_api/rest_api/register/__pycache__/forms.cpython-38.pyc
  practice-app/platon_api/rest_api/register/__pycache__/register.cpython-38.pyc
  practice-app/platon_api/rest_api/register/forms.py
  practice-app/platon_api/rest_api/register/register.py
  practice-app/platon_api/rest_api/register/register.txt
  practice-app/platon_api/rest_api/register/rest_api.register.register.html
  practice-app/platon_api/rest_api/register/test.py
  practice-app/platon_api/rest_api/serializers.py
  practice-app/platon_api/rest_api/tests.py
  practice-app/platon_api/rest_api/views.py
  practice-app/platon_api/templates/register/base.html
  practice-app/platon_api/templates/register/register_form.html
  practice-app/requirements.txt
Labels: Priority: High, Status: In Review

#69 Practice app register
  practice-app/platon_api/Dockerfile
  practice-app/platon_api/docker-compose.yml
  practice-app/platon_api/platon_api/__pycache__/__init__.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/settings.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/urls.cpython-38.pyc
  practice-app/platon_api/platon_api/__pycache__/wsgi.cpython-38.pyc
  practice-app/platon_api/platon_api/settings.py
  practice-app/platon_api/platon_api/urls.py
  practice-app/platon_api/rest_api/__pycache__/__init__.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/admin.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/models.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/tests.cpython-38.pyc
  practice-app/platon_api/rest_api/__pycache__/views.cpython-38.pyc
  practice-app/platon_api/rest_api/migrations/__init__.py
  practice-app/platon_api/rest_api/models.py
  practice-app/platon_api/rest_api/register/forms.py
  practice-app/platon_api/rest_api/register/register.py
  practice-app/platon_api/rest_api/register/register.txt
  practice-app/platon_api/rest_api/register/rest_api.register.register.html
  practice-app/platon_api/rest_api/register/test.py
  practice-app/platon_api/rest_api/serializers.py
  practice-app/platon_api/rest_api/tests.py
  practice-app/platon_api/rest_api/views.py
  practice-app/platon_api/templates/register/base.html
  practice-app/platon_api/templates/register/register_form.html
  practice-app/requirements.txt
Labels: Priority: High, Status: In Review, Type: New Feature

#72 Practice app delete user
  .gitignore
  practice-app/.vscode/settings.json
  practice-app/platon_api/manage.py
  practice-app/platon_api/platon_api/settings.py
  practice-app/platon_api/platon_api/urls.py
  practice-app/platon_api/rest_api/delete_user_t/__pycache__/delete_user_f.cpython-36.pyc
  practice-app/platon_api/rest_api/delete_user_t/__pycache__/unit_test.cpython-36.pyc
  practice-app/platon_api/rest_api/delete_user_t/delete_user_f.html
  practice-app/platon_api/rest_api/delete_user_t/delete_user_f.py
  practice-app/platon_api/rest_api/delete_user_t/delete_user_f.pyc
  practice-app/platon_api/rest_api/delete_user_t/unit_test.py
  practice-app/platon_api/rest_api/migrations/0001_initial.py
  practice-app/platon_api/rest_api/migrations/__pycache__/0001_initial.cpython-36.pyc
  practice-app/platon_api/rest_api/migrations/__pycache__/__init__.cpython-36.pyc
  practice-app/platon_api/rest_api/tests.py
  practice-app/platon_api/rest_api/views.py
Labels: Priority: High, Status: In Review
